# Generated by Django 5.2.16 on 2026-07-09 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('wp_term_id', models.BigIntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'industries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('wp_user_login', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('wp_user_id', models.BigIntegerField(unique=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='ImportLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(max_length=32)),
                ('wp_id', models.BigIntegerField()),
            ],
            options={
                'unique_together': {('model_label', 'wp_id')},
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('body', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True, max_length=500)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('headquarters', models.CharField(blank=True, max_length=255)),
                ('migrated_average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_metadesc', models.TextField(blank=True)),
                ('wp_post_id', models.BigIntegerField(unique=True)),
                ('wp_post_date', models.DateTimeField(blank=True, null=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='catalog.industry')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('body', models.TextField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reviewer_name', models.CharField(blank=True, max_length=255)),
                ('reviewer_location', models.CharField(blank=True, max_length=255)),
                ('wp_post_id', models.BigIntegerField(unique=True)),
                ('wp_post_date', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.brand')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='catalog.reviewer')),
            ],
            options={
                'ordering': ['-wp_post_date'],
            },
        ),
    ]
