# Generated by Django 5.2.16 on 2026-07-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='review_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['brand', '-rating', '-wp_post_date'], name='review_brand_top_idx'),
        ),
    ]
