#!/usr/bin/env bash
#
# Extract the compiled theme CSS from the running WordPress container and
# commit it to reference/theme.css for candidates to recreate as SCSS source.
#
# Run this ONCE (or whenever the theme stylesheet changes). The output is
# committed to the repo so candidates do not need the WP stack running just
# to see the target CSS.
#
# Usage:
#   ./scripts/extract-theme-css.sh
#
# Requires: the docker compose stack to be running (`make up`).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REFERENCE_DIR="${REPO_ROOT}/reference"
OUTPUT_FILE="${REFERENCE_DIR}/theme.css"
THEME_DIR="${REPO_ROOT}/wp-content/themes/consumer-reviews"

mkdir -p "${REFERENCE_DIR}"

# Prefer copying directly from the committed theme source — this is the exact
# CSS Apache serves, and it doesn't require the stack to be up.
if [[ -f "${THEME_DIR}/style.css" ]]; then
    echo "Copying ${THEME_DIR}/style.css → ${OUTPUT_FILE}"
    {
        cat <<'EOF'
/*
 * Theme CSS reference for the WP → Django migration challenge.
 *
 * This file is the COMPILED OUTPUT of the WordPress theme. Your job is to
 * produce SCSS source files that compile to equivalent CSS, organized the
 * way a senior frontend engineer would organize them.
 *
 * Equivalence is structural — design tokens, partials, naming, separation
 * of concerns — not byte-for-byte identical output.
 *
 * Do not edit this file. Generate your own SCSS under frontend/scss/.
 */

EOF
        # Strip the WP theme metadata header (lines 1-13 in the source).
        # WordPress requires it; candidates don't need to see it.
        tail -n +14 "${THEME_DIR}/style.css"
    } > "${OUTPUT_FILE}"
    echo "Wrote ${OUTPUT_FILE} ($(wc -l < "${OUTPUT_FILE}") lines)"
    exit 0
fi

# Fallback: fetch from the running container if the source file is missing
# for some reason.
echo "Theme source not found locally; fetching from running WP stack…"

if ! curl -fsS -o /dev/null http://localhost:8080/; then
    echo "ERROR: WordPress is not reachable at http://localhost:8080" >&2
    echo "Start the stack first: make up" >&2
    exit 1
fi

CSS_URL="http://localhost:8080/wp-content/themes/consumer-reviews/style.css"
curl -fsS "${CSS_URL}" > "${OUTPUT_FILE}"
echo "Wrote ${OUTPUT_FILE} ($(wc -l < "${OUTPUT_FILE}") lines) from ${CSS_URL}"
